# Generated by Django 5.1.2 on 2024-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('eletroportateis', 'Eletroportáteis'), ('moveis', 'Móveis'), ('geladeiras', 'Geladeiras'), ('smartphones', 'Smartphones'), ('eletronicos', 'Eletrônicos')], max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
